openapi: 3.0.0
info:
  title: Pismo Interview Api
  description: Pismo interview project.
  version: 1.0.0

paths:
  /accounts:
    post:
      summary: Create an account.
      description: Create an account by document number.
      operationId: create
      tags:
        - Account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountRequest'
      responses:
        '201':
          description: Account created

components:
  schemas:
    AccountRequest:
      properties:
        document_number:
          type: string
          description: Document number
          example: "12345678900"
      required:
        - document_number