openapi: 3.0.0
info:
  title: Pismo Interview Api
  description: Pismo interview project.
  version: 1.0.0

paths:
  /accounts:
    post:
      summary: Create an account.
      description: Create an account by document number.
      operationId: create
      tags:
        - Customer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountRequest'
      responses:
        '201':
          description: Account created
  /accounts/{accountId}:
    get:
      summary: Find an account.
      description: Find an account by id.
      operationId: find
      tags:
        - Customer
      parameters:
        - name: accountId
          in: path
          required: true
          description: Account id
          example: 1
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '200':
          description: Account returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountResponse'
  /transactions:
    post:
      summary: Create a new transaction.
      description: Create new transaction.
      operationId: createTransaction
      tags:
        - Customer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionRequest'
      responses:
        '201':
          description: Transaction created

components:
  schemas:
    AccountRequest:
      type: object
      properties:
        document_number:
          type: string
          description: Document number
          example: "12345678900"
          minLength: 1
      required:
        - document_number
    AccountResponse:
      type: object
      properties:
        account_id:
          type: integer
          format: int64
          description: Account id
          example: "1"
        document_number:
          type: string
          description: Document number
          example: "12345678900"
    TransactionRequest:
      type: object
      properties:
        account_id:
          type: integer
          format: int64
          example: 1
        operation_type_id:
          type: integer
          format: int64
          example: 1
        amount:
          type: bigDecimal
          example: 123.45
      required:
        - account_id
        - operation_type_id
        - amount
    ErrorResponse:
      type: object
      properties:
        status:
          type: integer
        message:
          type: string
        validationErros:
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    ValidationError:
      type: object
      properties:
        field:
          type: string
        message:
          type: string
